export interface RedisCommandArg {
  name: string;
  type:
    | "string"
    | "integer"
    | "double"
    | "key"
    | "pattern"
    | "field"
    | "member"
    | "index";
  optional?: boolean;
  multiple?: boolean;
}

export interface RedisCommand {
  name: string;
  summary: string;
  syntax: string;
  group: string;
  since: string;
  complexity?: string;
  args?: RedisCommandArg[];
}

export const REDIS_COMMANDS: RedisCommand[] = [
  // String Commands
  {
    name: "GET",
    summary: "Get the value of a key",
    syntax: "GET key",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
    args: [{ name: "key", type: "key" }],
  },
  {
    name: "SET",
    summary: "Set the string value of a key",
    syntax: "SET key value [EX seconds|PX milliseconds] [NX|XX] [GET]",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
    args: [
      { name: "key", type: "key" },
      { name: "value", type: "string" },
    ],
  },
  {
    name: "SETEX",
    summary: "Set the value and expiration of a key",
    syntax: "SETEX key seconds value",
    group: "string",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "SETNX",
    summary: "Set the value of a key, only if the key does not exist",
    syntax: "SETNX key value",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "APPEND",
    summary: "Append a value to a key",
    syntax: "APPEND key value",
    group: "string",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "INCR",
    summary: "Increment the integer value of a key by one",
    syntax: "INCR key",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "INCRBY",
    summary: "Increment the integer value of a key by the given amount",
    syntax: "INCRBY key increment",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "INCRBYFLOAT",
    summary: "Increment the float value of a key by the given amount",
    syntax: "INCRBYFLOAT key increment",
    group: "string",
    since: "2.6.0",
    complexity: "O(1)",
  },
  {
    name: "DECR",
    summary: "Decrement the integer value of a key by one",
    syntax: "DECR key",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "DECRBY",
    summary: "Decrement the integer value of a key by the given number",
    syntax: "DECRBY key decrement",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "GETRANGE",
    summary: "Get a substring of the string stored at a key",
    syntax: "GETRANGE key start end",
    group: "string",
    since: "2.4.0",
    complexity: "O(N)",
  },
  {
    name: "SETRANGE",
    summary:
      "Overwrite part of a string at key starting at the specified offset",
    syntax: "SETRANGE key offset value",
    group: "string",
    since: "2.2.0",
    complexity: "O(1)",
  },
  {
    name: "STRLEN",
    summary: "Get the length of the value stored in a key",
    syntax: "STRLEN key",
    group: "string",
    since: "2.2.0",
    complexity: "O(1)",
  },
  {
    name: "GETSET",
    summary: "Set the string value of a key and return its old value",
    syntax: "GETSET key value",
    group: "string",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "MGET",
    summary: "Get the values of all the given keys",
    syntax: "MGET key [key ...]",
    group: "string",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "MSET",
    summary: "Set multiple keys to multiple values",
    syntax: "MSET key value [key value ...]",
    group: "string",
    since: "1.0.1",
    complexity: "O(N)",
  },

  // Hash Commands
  {
    name: "HGET",
    summary: "Get the value of a hash field",
    syntax: "HGET key field",
    group: "hash",
    since: "2.0.0",
    complexity: "O(1)",
    args: [
      { name: "key", type: "key" },
      { name: "field", type: "field" },
    ],
  },
  {
    name: "HSET",
    summary: "Set the string value of a hash field",
    syntax: "HSET key field value [field value ...]",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "field", type: "field" },
      { name: "value", type: "string" },
    ],
  },
  {
    name: "HSETNX",
    summary: "Set the value of a hash field, only if the field does not exist",
    syntax: "HSETNX key field value",
    group: "hash",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "HMGET",
    summary: "Get the values of all the given hash fields",
    syntax: "HMGET key field [field ...]",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HMSET",
    summary: "Set multiple hash fields to multiple values",
    syntax: "HMSET key field value [field value ...]",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HGETALL",
    summary: "Get all the fields and values in a hash",
    syntax: "HGETALL key",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HDEL",
    summary: "Delete one or more hash fields",
    syntax: "HDEL key field [field ...]",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HEXISTS",
    summary: "Determine if a hash field exists",
    syntax: "HEXISTS key field",
    group: "hash",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "HKEYS",
    summary: "Get all the fields in a hash",
    syntax: "HKEYS key",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HVALS",
    summary: "Get all the values in a hash",
    syntax: "HVALS key",
    group: "hash",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "HLEN",
    summary: "Get the number of fields in a hash",
    syntax: "HLEN key",
    group: "hash",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "HINCRBY",
    summary: "Increment the integer value of a hash field by the given number",
    syntax: "HINCRBY key field increment",
    group: "hash",
    since: "2.0.0",
    complexity: "O(1)",
  },
  {
    name: "HINCRBYFLOAT",
    summary: "Increment the float value of a hash field by the given amount",
    syntax: "HINCRBYFLOAT key field increment",
    group: "hash",
    since: "2.6.0",
    complexity: "O(1)",
  },

  // List Commands
  {
    name: "LPUSH",
    summary: "Prepend one or multiple values to a list",
    syntax: "LPUSH key element [element ...]",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "element", type: "string", multiple: true },
    ],
  },
  {
    name: "RPUSH",
    summary: "Append one or multiple values to a list",
    syntax: "RPUSH key element [element ...]",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "element", type: "string", multiple: true },
    ],
  },
  {
    name: "LPOP",
    summary: "Remove and get the first element in a list",
    syntax: "LPOP key [count]",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [{ name: "key", type: "key" }],
  },
  {
    name: "RPOP",
    summary: "Remove and get the last element in a list",
    syntax: "RPOP key [count]",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [{ name: "key", type: "key" }],
  },
  {
    name: "LRANGE",
    summary: "Get a range of elements from a list",
    syntax: "LRANGE key start stop",
    group: "list",
    since: "1.0.0",
    complexity: "O(S+N)",
    args: [
      { name: "key", type: "key" },
      { name: "start", type: "index" },
      { name: "stop", type: "index" },
    ],
  },
  {
    name: "LLEN",
    summary: "Get the length of a list",
    syntax: "LLEN key",
    group: "list",
    since: "1.0.0",
    complexity: "O(1)",
    args: [{ name: "key", type: "key" }],
  },
  {
    name: "LINDEX",
    summary: "Get an element from a list by its index",
    syntax: "LINDEX key index",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "index", type: "index" },
    ],
  },
  {
    name: "LSET",
    summary: "Set the value of an element in a list by its index",
    syntax: "LSET key index element",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "index", type: "index" },
      { name: "element", type: "string" },
    ],
  },
  {
    name: "LREM",
    summary: "Remove elements from a list",
    syntax: "LREM key count element",
    group: "list",
    since: "1.0.0",
    complexity: "O(N+M)",
  },
  {
    name: "LTRIM",
    summary: "Trim a list to the specified range",
    syntax: "LTRIM key start stop",
    group: "list",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "LINSERT",
    summary: "Insert an element before or after another element in a list",
    syntax: "LINSERT key BEFORE|AFTER pivot element",
    group: "list",
    since: "2.2.0",
    complexity: "O(N)",
  },

  // Set Commands
  {
    name: "SADD",
    summary: "Add one or more members to a set",
    syntax: "SADD key member [member ...]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "member", type: "member", multiple: true },
    ],
  },
  {
    name: "SREM",
    summary: "Remove one or more members from a set",
    syntax: "SREM key member [member ...]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
    args: [
      { name: "key", type: "key" },
      { name: "member", type: "member", multiple: true },
    ],
  },
  {
    name: "SMEMBERS",
    summary: "Get all the members in a set",
    syntax: "SMEMBERS key",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
    args: [{ name: "key", type: "key" }],
  },
  {
    name: "SISMEMBER",
    summary: "Determine if a given value is a member of a set",
    syntax: "SISMEMBER key member",
    group: "set",
    since: "1.0.0",
    complexity: "O(1)",
    args: [
      { name: "key", type: "key" },
      { name: "member", type: "member" },
    ],
  },
  {
    name: "SCARD",
    summary: "Get the number of members in a set",
    syntax: "SCARD key",
    group: "set",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "SPOP",
    summary: "Remove and return one or multiple random members from a set",
    syntax: "SPOP key [count]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "SRANDMEMBER",
    summary: "Get one or multiple random members from a set",
    syntax: "SRANDMEMBER key [count]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "SUNION",
    summary: "Add multiple sets",
    syntax: "SUNION key [key ...]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "SINTER",
    summary: "Intersect multiple sets",
    syntax: "SINTER key [key ...]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N*M)",
  },
  {
    name: "SDIFF",
    summary: "Subtract multiple sets",
    syntax: "SDIFF key [key ...]",
    group: "set",
    since: "1.0.0",
    complexity: "O(N)",
  },

  // Sorted Set Commands
  {
    name: "ZADD",
    summary: "Add one or more members to a sorted set, or update its score",
    syntax:
      "ZADD key [NX|XX] [GT|LT] [CH] [INCR] score member [score member ...]",
    group: "zset",
    since: "1.2.0",
    complexity: "O(log(N))",
  },
  {
    name: "ZREM",
    summary: "Remove one or more members from a sorted set",
    syntax: "ZREM key member [member ...]",
    group: "zset",
    since: "1.2.0",
    complexity: "O(M*log(N))",
  },
  {
    name: "ZRANGE",
    summary: "Return a range of members in a sorted set",
    syntax: "ZRANGE key start stop [WITHSCORES]",
    group: "zset",
    since: "1.2.0",
    complexity: "O(log(N)+M)",
  },
  {
    name: "ZREVRANGE",
    summary:
      "Return a range of members in a sorted set, by index, with scores ordered high to low",
    syntax: "ZREVRANGE key start stop [WITHSCORES]",
    group: "zset",
    since: "1.2.0",
    complexity: "O(log(N)+M)",
  },
  {
    name: "ZRANK",
    summary: "Determine the index of a member in a sorted set",
    syntax: "ZRANK key member",
    group: "zset",
    since: "2.0.0",
    complexity: "O(log(N))",
  },
  {
    name: "ZREVRANK",
    summary:
      "Determine the index of a member in a sorted set, with scores ordered high to low",
    syntax: "ZREVRANK key member",
    group: "zset",
    since: "2.0.0",
    complexity: "O(log(N))",
  },
  {
    name: "ZSCORE",
    summary: "Get the score associated with the given member in a sorted set",
    syntax: "ZSCORE key member",
    group: "zset",
    since: "1.2.0",
    complexity: "O(1)",
  },
  {
    name: "ZCARD",
    summary: "Get the number of members in a sorted set",
    syntax: "ZCARD key",
    group: "zset",
    since: "1.2.0",
    complexity: "O(1)",
  },
  {
    name: "ZINCRBY",
    summary: "Increment the score of a member in a sorted set",
    syntax: "ZINCRBY key increment member",
    group: "zset",
    since: "1.2.0",
    complexity: "O(log(N))",
  },
  {
    name: "ZCOUNT",
    summary:
      "Count the members in a sorted set with scores within the given values",
    syntax: "ZCOUNT key min max",
    group: "zset",
    since: "2.0.0",
    complexity: "O(log(N))",
  },
  {
    name: "ZRANGEBYSCORE",
    summary: "Return a range of members in a sorted set, by score",
    syntax: "ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]",
    group: "zset",
    since: "1.0.5",
    complexity: "O(log(N)+M)",
  },

  // Generic Commands
  {
    name: "DEL",
    summary: "Delete a key",
    syntax: "DEL key [key ...]",
    group: "generic",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "EXISTS",
    summary: "Determine if a key exists",
    syntax: "EXISTS key [key ...]",
    group: "generic",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "EXPIRE",
    summary: "Set a key's time to live in seconds",
    syntax: "EXPIRE key seconds [NX|XX|GT|LT]",
    group: "generic",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "EXPIREAT",
    summary: "Set the expiration for a key as a UNIX timestamp",
    syntax: "EXPIREAT key timestamp [NX|XX|GT|LT]",
    group: "generic",
    since: "1.2.0",
    complexity: "O(1)",
  },
  {
    name: "TTL",
    summary: "Get the time to live for a key in seconds",
    syntax: "TTL key",
    group: "generic",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "PTTL",
    summary: "Get the time to live for a key in milliseconds",
    syntax: "PTTL key",
    group: "generic",
    since: "2.6.0",
    complexity: "O(1)",
  },
  {
    name: "PERSIST",
    summary: "Remove the expiration from a key",
    syntax: "PERSIST key",
    group: "generic",
    since: "2.2.0",
    complexity: "O(1)",
  },
  {
    name: "KEYS",
    summary: "Find all keys matching the given pattern",
    syntax: "KEYS pattern",
    group: "generic",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "SCAN",
    summary: "Incrementally iterate the keys space",
    syntax: "SCAN cursor [MATCH pattern] [COUNT count] [TYPE type]",
    group: "generic",
    since: "2.8.0",
    complexity: "O(1)",
  },
  {
    name: "TYPE",
    summary: "Determine the type stored at key",
    syntax: "TYPE key",
    group: "generic",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "RENAME",
    summary: "Rename a key",
    syntax: "RENAME key newkey",
    group: "generic",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "RENAMENX",
    summary: "Rename a key, only if the new key does not exist",
    syntax: "RENAMENX key newkey",
    group: "generic",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "DUMP",
    summary:
      "Return a serialized version of the value stored at the specified key",
    syntax: "DUMP key",
    group: "generic",
    since: "2.6.0",
    complexity: "O(1)",
  },
  {
    name: "RESTORE",
    summary: "Create a key using the provided serialized value",
    syntax: "RESTORE key ttl serialized-value [REPLACE]",
    group: "generic",
    since: "2.6.0",
    complexity: "O(1)",
  },

  // Server Commands
  {
    name: "INFO",
    summary: "Get information and statistics about the server",
    syntax: "INFO [section]",
    group: "server",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "PING",
    summary: "Ping the server",
    syntax: "PING [message]",
    group: "server",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "FLUSHDB",
    summary: "Remove all keys from the current database",
    syntax: "FLUSHDB [ASYNC|SYNC]",
    group: "server",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "FLUSHALL",
    summary: "Remove all keys from all databases",
    syntax: "FLUSHALL [ASYNC|SYNC]",
    group: "server",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "DBSIZE",
    summary: "Return the number of keys in the selected database",
    syntax: "DBSIZE",
    group: "server",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "CLIENT",
    summary: "Client connection commands",
    syntax: "CLIENT subcommand [argument [argument ...]]",
    group: "server",
    since: "2.4.0",
    complexity: "Varies",
  },
  {
    name: "CONFIG",
    summary: "Get or set configuration parameters",
    syntax: "CONFIG subcommand [argument [argument ...]]",
    group: "server",
    since: "2.0.0",
    complexity: "Varies",
  },
  {
    name: "SAVE",
    summary: "Synchronously save the dataset to disk",
    syntax: "SAVE",
    group: "server",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "BGSAVE",
    summary: "Asynchronously save the dataset to disk",
    syntax: "BGSAVE",
    group: "server",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "SHUTDOWN",
    summary:
      "Synchronously save the dataset to disk and then shut down the server",
    syntax: "SHUTDOWN [NOSAVE|SAVE]",
    group: "server",
    since: "1.0.0",
    complexity: "O(N)",
  },
  {
    name: "SLOWLOG",
    summary: "Manages the Redis slow queries log",
    syntax: "SLOWLOG subcommand [argument]",
    group: "server",
    since: "2.2.12",
    complexity: "Varies",
  },

  // Connection Commands
  {
    name: "AUTH",
    summary: "Authenticate to the server",
    syntax: "AUTH [username] password",
    group: "connection",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "SELECT",
    summary: "Change the selected database for the current connection",
    syntax: "SELECT index",
    group: "connection",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "QUIT",
    summary: "Close the connection",
    syntax: "QUIT",
    group: "connection",
    since: "1.0.0",
    complexity: "O(1)",
  },
  {
    name: "ECHO",
    summary: "Echo the given string",
    syntax: "ECHO message",
    group: "connection",
    since: "1.0.0",
    complexity: "O(1)",
  },

  // Pub/Sub Commands
  {
    name: "PUBLISH",
    summary: "Post a message to a channel",
    syntax: "PUBLISH channel message",
    group: "pubsub",
    since: "2.0.0",
    complexity: "O(N+M)",
  },
  {
    name: "SUBSCRIBE",
    summary: "Listen for messages published to the given channels",
    syntax: "SUBSCRIBE channel [channel ...]",
    group: "pubsub",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "UNSUBSCRIBE",
    summary: "Stop listening for messages posted to the given channels",
    syntax: "UNSUBSCRIBE [channel [channel ...]]",
    group: "pubsub",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "PSUBSCRIBE",
    summary:
      "Listen for messages published to channels matching the given patterns",
    syntax: "PSUBSCRIBE pattern [pattern ...]",
    group: "pubsub",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "PUNSUBSCRIBE",
    summary:
      "Stop listening for messages posted to channels matching the given patterns",
    syntax: "PUNSUBSCRIBE [pattern [pattern ...]]",
    group: "pubsub",
    since: "2.0.0",
    complexity: "O(N)",
  },
  {
    name: "PUBSUB",
    summary: "Inspect the state of the Pub/Sub subsystem",
    syntax: "PUBSUB subcommand [argument [argument ...]]",
    group: "pubsub",
    since: "2.8.0",
    complexity: "Varies",
  },

  // Stream Commands
  {
    name: "XADD",
    summary: "Appends a new entry to a stream",
    syntax:
      "XADD key [NOMKSTREAM] [MAXLEN|MINID [=|~] threshold [LIMIT count]] *|ID field value [field value ...]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(1)",
  },
  {
    name: "XRANGE",
    summary:
      "Return a range of elements in a stream, with IDs matching the specified range",
    syntax: "XRANGE key start end [COUNT count]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(N)",
  },
  {
    name: "XREVRANGE",
    summary:
      "Return a range of elements in a stream, with IDs matching the specified range, in reverse order",
    syntax: "XREVRANGE key end start [COUNT count]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(N)",
  },
  {
    name: "XLEN",
    summary: "Return the number of entries in a stream",
    syntax: "XLEN key",
    group: "stream",
    since: "5.0.0",
    complexity: "O(1)",
  },
  {
    name: "XREAD",
    summary: "Return never seen elements in multiple streams",
    syntax:
      "XREAD [COUNT count] [BLOCK milliseconds] STREAMS key [key ...] ID [ID ...]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(N)",
  },
  {
    name: "XDEL",
    summary: "Removes the specified entries from the stream",
    syntax: "XDEL key ID [ID ...]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(1)",
  },
  {
    name: "XTRIM",
    summary: "Trims the stream to a specified number of items",
    syntax: "XTRIM key MAXLEN|MINID [=|~] threshold [LIMIT count]",
    group: "stream",
    since: "5.0.0",
    complexity: "O(N)",
  },
];

// Helper functions
export function getCommandSuggestions(partial: string): RedisCommand[] {
  if (!partial) return [];

  const upper = partial.toUpperCase();
  return REDIS_COMMANDS.filter((cmd) => cmd.name.startsWith(upper)).slice(
    0,
    10,
  ); // Limit to 10 suggestions
}

export function getCommand(name: string): RedisCommand | undefined {
  return REDIS_COMMANDS.find((cmd) => cmd.name === name.toUpperCase());
}
